# Generated by Django 3.2.8 on 2021-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenVpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_send', models.TextField(db_column='Имя отправителя')),
                ('user_name_get', models.TextField(db_column='Имя Получателя')),
                ('message', models.TextField(db_column='Сообщение')),
            ],
        ),
    ]
